### ISSUE TITLE
ChartRepository using helm home fails

### ISSUE THREAD

**Issue by avichap** [microbean/microbean-helm#80] opened 2018-01-30 10:09 UTC
Creating ChartRepository  with (name , url ) constructor running on machine with initialized HELM home directory fails with NPE.

this is due 
if (!Files.isDirectory(indexCacheDirectory)) {
        throw new IllegalArgumentException("!Files.isDirectory(indexCacheDirectory): " + indexCacheDirectory);
      }

should have test the this.indexCacheDirectory instead.

**Comment by ljnelson** [comment] 2018-01-30 20:13
Thanks for the bug report!  I don't think the change you suggest will fix the issue, since at [line 337](https://github.com/microbean/microbean-helm/blob/v2.7.0.1.0.41/src/main/java/org/microbean/helm/chart/repository/ChartRepository.java#L337) the two references are the same.  Digging to understand this more.

**Comment by ljnelson** [comment] 2018-01-30 21:29
I stand humbly corrected; they are _not_ the same reference.  I have a reproducer and a fix will be in shortly.

**Closed** 2018-01-31 00:39 UTC
Labels: bug, problem understood
