### ISSUE TITLE
Chart Values are not getting overidden

### ISSUE THREAD

**Issue by vinapp** [microbean/microbean-helm#182] opened 2018-09-15 20:24 UTC
Looks like the values are not getting overidden even when i use setRaw(yamlString). Below is the code. Here I am trying to override the image repository.

Code:

```
final Map<String, Object> yaml = new LinkedHashMap<>();
yaml.put("image.repository", "registry/test/my-server");
final String yamlString = new Yaml().dump(yaml);
requestBuilder.getValuesBuilder().setRaw(yamlString);
final Future<InstallReleaseResponse> releaseFuture = releaseManager.install(requestBuilder, chart);
```

This (override) works fine from the helm command line.

Currently I am using microbean-helm version 2.8.2.1.1.1 - os.detected.classifier=osx-x86_64

**Comment by ljnelson** [comment] 2018-09-15 22:54
Just a quick question: are you doing the same stuff as the [example](https://microbean.github.io/microbean-helm/examples.html)?

**Comment by ljnelson** [comment] 2018-09-15 23:00
(I’m on my phone but yes it looks like that’s what you’re doing. The example works; I’ll look at your scenario soon.)

**Comment by ljnelson** [comment] 2018-09-15 23:27
You appear to be doing everything correctly.  Here's the problem: there's not much I can do.  Both the `Request.Builder` and `Values.Builder` interfaces are generated (I didn't write them).  They do whatever they do.  As I mentioned, the example works.  Is it possible that you are setting a YAML value that isn't actually being retrieved or parsed?  That is, perhaps the value you are passing is not the one that you meant to pass; maybe it's supposed to be `imageRepository` or something.

**Comment by ljnelson** [comment] 2018-09-15 23:34
Ah, in fact it's a YAML problem.

Either you are (a) trying to actually set a scalar key named `image.repository` to a value or (b) trying to set a scalar key named `repository` under a map key named `image` to a value.  As you have written things, you are doing (a); I suspect you _want_ to do (b).

You have a couple of choices.  Remember that ultimately you're trying to set a raw YAML string, so how you produce that string is up to you.  If you choose to build a `Map` and then have the `Yaml` object `dump` it for you, then you want to do something ponderous like this:

    // untested
    final Map<String, Object> repositoryMap = new HashMap<>();
    repositoryMap.put("repository", "registry/test/my-server");
    final Map<String, Object> imageMap = new HashMap<>();
    imageMap.put("image", repositoryMap);

Then `dump` `imageMap`.

Alternatively you could just build the string directly:

    requestBuilder.getValuesBuilder().setRaw("image:\n  repository: registry/test/my-server");

Closing as this is not a bug, unless you consider all of YAML itself to be a giant horrible bug foisted upon the universe (which I do) 😄 .

**Closed by ljnelson** 2018-09-15 23:34 UTC
Labels: YAML, problem understood, wontfix

**Comment by vinapp** [comment] 2018-09-16 07:12
@ljnelson thanks a lot it saved my time. It would be good if the example [sample](https://microbean.github.io/microbean-helm/examples.html) is updated for "scalar keys" as well. Thanks Again !!!
