### ISSUE TITLE
Is there a simple way to load a chart as an InputStream?

### ISSUE THREAD

**Issue by seglo** [microbean/microbean-helm#175] opened 2018-06-19 18:53 UTC
I have a project which bundles a chart as a resource, but I can't find a `ChartLoader` implementation that can accept an `InputStream`, though internally this seems to be done.  Is there a way I can load a tarballed chart from an `InputStream`, without having to create my own `ChartLoader`?

**Comment by seglo** [comment] 2018-06-19 19:36
I cannibalised the `URLChartLoader` and came up with this.

```
package org.microbean.helm.chart;

import hapi.chart.ChartOuterClass.Chart;
import org.kamranzafar.jtar.TarInputStream;

import java.io.BufferedInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.Collection;
import java.util.IdentityHashMap;
import java.util.Iterator;
import java.util.Map.Entry;
import java.util.Objects;
import java.util.zip.GZIPInputStream;

/**
 * ChartLoader to load a tarballed helm chart from a local resource path.
 */
public class InputStreamChartLoader extends StreamOrientedChartLoader<InputStream> {
    private final IdentityHashMap<AutoCloseable, Void> closeables;

    public InputStreamChartLoader() {
        super();
        this.closeables = new IdentityHashMap<>();
    }

    @Override
    public Chart.Builder load(final Chart.Builder parent, final InputStream source) throws IOException {
        final Chart.Builder returnValue = this.load(parent, toNamedInputStreamEntries(source));
        if (returnValue == null) {
            throw new IllegalStateException("load(toNamedInputStreamEntries(source)) == null; source: " + source);
        }
        return returnValue;
    }


    @Override
    protected Iterable<? extends Entry<? extends String, ? extends InputStream>> toNamedInputStreamEntries(final InputStream inputStream) throws IOException {
        Objects.requireNonNull(inputStream);

        final TarInputStream tarInputStream = new TarInputStream(new GZIPInputStream(new BufferedInputStream(inputStream)));
        this.closeables.put(tarInputStream, null);
        final TapeArchiveChartLoader loader = new TapeArchiveChartLoader();
        this.closeables.put(loader, null);
        return loader.toNamedInputStreamEntries(tarInputStream);
    }

    @Override
    public void close() throws IOException {
        if (!this.closeables.isEmpty()) {
            final Collection<? extends AutoCloseable> keys = this.closeables.keySet();
            if (keys != null && !keys.isEmpty()) {
                final Iterator<? extends AutoCloseable> iterator = keys.iterator();
                if (iterator != null) {
                    while (iterator.hasNext()) {
                        final AutoCloseable closeable = iterator.next();
                        if (closeable != null) {
                            try {
                                closeable.close();
                            } catch (final IOException | RuntimeException throwMe) {
                                throw throwMe;
                            } catch (final Exception willNeverHappen) {
                                throw new AssertionError(willNeverHappen);
                            }
                        }
                        iterator.remove();
                    }
                }
            }
        }
        assert this.closeables.isEmpty();
    }

}
```

**Comment by seglo** [comment] 2018-06-19 19:37
but it must reside in `org.microbean.helm.chart` to access the protected member `TapeArchiveChartLoader.toNamedInputStreamEntries`

**Comment by ljnelson** [comment] 2018-06-19 22:20
Well, a `TapeArchiveChartLoader` takes a `TarInputStream`.  Is that good enough?

The problem is that given an arbitrary `InputStream` that you "want" to represent a chart, you don't know how to convert the bytes into the relevant chart constructs until you know what kind of stream it is.

So there are two classes that I've written: [`TapeArchiveChartLoader`](https://microbean.github.io/microbean-helm/apidocs/org/microbean/helm/chart/TapeArchiveChartLoader.html) and [`ZipArchiveChartLoader`](https://microbean.github.io/microbean-helm/apidocs/org/microbean/helm/chart/ZipInputStreamChartLoader.html).

Another problem is Helm's schizophrenia around what exactly a chart _is_.  You would think you could represent a chart in a number of different media, but computing the signature of a chart requires that the chart be stored in a `.tar` file fundamentally.  Is that a necessary property of charts?  I don't know, and it doesn't appear that Helm developers have ever thought about any other kind of packaging format.  So tread carefully.

**Comment by ljnelson** [comment] 2018-06-19 22:21
You also write:
> it must reside in org.microbean.helm.chart to access the protected member TapeArchiveChartLoader.toNamedInputStreamEntries

…but that's not true; `protected` in Java simply means that it's accessible to subclasses (in any package).

**Comment by seglo** [comment] 2018-06-19 23:02
> Well, a TapeArchiveChartLoader takes a TarInputStream. Is that good enough?

Yes, you're right I can just do that.  My mistake.

> …but that's not true; protected in Java simply means that it's accessible to subclasses (in any package).

I think where I got confused was that `URLChartLoader` was accessing the `TapeArchiveChartLoader.toNamedInputStreamEntries` even though it was a protected member.  I guess because they share a same parent class?  My subclass implementation worked in a test, but failed in the app I was using it in because it uses multiple class loaders.  I received an `IllegalAccessException`, not an `IllegalStateException` like I originally reported.

Anyway, I was thrashing around a bit, so thanks for your comments.  I'll provide an update tomorrow and close the issue.

**Comment by ljnelson** [comment] 2018-06-19 23:08
> I think where I got confused was that URLChartLoader was accessing the TapeArchiveChartLoader.toNamedInputStreamEntries even though it was a protected member. I guess because they share a same parent class?

No, you're right: `URLChartLoader` definitely accesses that method on loaders it creates internally.  It can do that because `protected` in Java as you may or may not know (not sure) means "available to subclasses (in any package) and other members of the same package".  There may be a case for making this method `public`, but I haven't really seen it yet.

I think the combination of `TapeArchiveChartLoader`, which is the only "official" chart loader if you believe that charts must fundamentally be tape archives, and `ZipArchiveChartLoader`, which is my experimental one for loading charts from `.jar` files (but it won't work with signed charts since their signature is derived from their "tarness"), plus `URLChartLoader`, which figures out which of those to construct and use internally, will take you wherever you need to go.

**Comment by ljnelson** [comment] 2018-06-28 16:15
Going to close this unless you object.

**Comment by seglo** [comment] 2018-07-03 16:37
Go ahead.  For reference I ended up using the `TapeArchiveChartLoader` directly as you suggested.

```
        val stream: InputStream = getClass.getResourceAsStream(path)
        val tarInputStream = new TarInputStream(new GZIPInputStream(new BufferedInputStream(stream)))
        val chartLoader = new TapeArchiveChartLoader()
        val chart = chartLoader.load(tarInputStream)
        chartLoader.close()
```

**Closed** 2018-07-03 16:38 UTC
